version: '3.8'

services:
  spark:
    build: .
    container_name: spark-container
    hostname: spark-master
    ports:
      - "4040:4040" # UI PySpark
      - "8080:8080" # UI Spark
      - "7077:7077" # Porta do cluster Spark
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
