services:
  spark:
    build: ./docker
    container_name: spark-container
    hostname: spark-master
    ports:
      - "4040:4040" # UI PySpark
      - "9080:9080" # UI Spark
      - "7077:7077" # Porta do cluster Spark
      - "8888:8888" # Jupyter Notebook
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
